# app/config/config.yml

liip_imagine:
    driver: "gd"
    filter_sets:

        # name our filter set "my_thumb_filter"
        300x450:
            filters:

                # use and setup the "thumbnail" filter
                thumbnail:

                    # set the thumbnail size to "32x32" pixels
                    size: [300, 450]

                    # crop the input image, if required
                    mode: outbound